<?php

namespace AppBundle\Repository;

/**
 * AgendaCompetenzeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgendaCompetenzeRepository extends \Doctrine\ORM\EntityRepository
{
}
