<?php

namespace AppBundle\Repository;

/**
 * CompetenzeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetenzeRepository extends \Doctrine\ORM\EntityRepository
{
}
