<?php

namespace AppBundle\Repository;

/**
 * Setup_competenzeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Setup_competenzeRepository extends \Doctrine\ORM\EntityRepository
{
}
